/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatpatt;

import javax.swing.*;
import java.awt.*;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

class ImageRenderer extends DefaultListCellRenderer {

    @Override
    public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value instanceof ImageIcon) {
            label.setIcon((ImageIcon) value);
            label.setText("");
        }
        return label;
    }
}

public class signup extends javax.swing.JFrame {

    public class DatabaseConnection {

        private static final String URL = "jdbc:mysql://localhost:3306/users";
        private static final String USER = "root";
        private static final String PASSWORD = "1234";

        public static Connection getConnection() throws SQLException {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); // MySQL JDBC sürücüsünü yükle
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
                throw new SQLException("JDBC Driver not found", e);
            }
            return DriverManager.getConnection(URL, USER, PASSWORD);
        }
    }

   public void saveUser(String username, String email, String password, String bio, String gender, String profilePicturePath) {
        // Kullanıcı adı için regex (sadece harf ve rakamlardan oluşmalı ve 3-15 karakter uzunluğunda olmalı)
        String usernameRegex = "^[a-zA-Z0-9]{3,15}$";
        // E-posta için regex
        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
        // Şifre için regex (en az bir harf ve bir rakam içermeli ve 6-20 karakter uzunluğunda olmalı)
        String passwordRegex = "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,20}$";

        // Regex desenlerini derleyin
        Pattern usernamePattern = Pattern.compile(usernameRegex);
        Pattern emailPattern = Pattern.compile(emailRegex);
        Pattern passwordPattern = Pattern.compile(passwordRegex);

        // Girişleri regex ile doğrulayın
        Matcher usernameMatcher = usernamePattern.matcher(username);
        Matcher emailMatcher = emailPattern.matcher(email);
        Matcher passwordMatcher = passwordPattern.matcher(password);

        if (!usernameMatcher.matches()) {
            JOptionPane.showMessageDialog(null, "Geçersiz kullanıcı adı. Kullanıcı adı sadece harf ve rakamlardan oluşmalı ve 3-15 karakter uzunluğunda olmalıdır.");
            return;
        }

        if (!emailMatcher.matches()) {
            JOptionPane.showMessageDialog(null, "Geçersiz e-posta adresi.");
            return;
        }

        if (!passwordMatcher.matches()) {
            JOptionPane.showMessageDialog(null, "Geçersiz şifre. Şifre en az bir harf ve bir rakam içermeli ve 6-20 karakter uzunluğunda olmalıdır.");
            return;
        }

        String query = "INSERT INTO user (username, email, password, bio, cinsiyet, profile_picture) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, username);
            stmt.setString(2, email);
            stmt.setString(3, password);
            stmt.setString(4, bio);
            stmt.setString(5, gender);
            stmt.setString(6, profilePicturePath); // Dosya yolunu ekleyin

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Kullanıcı başarıyla kaydedildi!");
            login loginFrame = new login();
            loginFrame.setVisible(true);
            loginFrame.pack();
            loginFrame.setLocationRelativeTo(null);
            this.dispose();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Kullanıcı kaydedilemedi: " + e.getMessage());
        }
    }

    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        avatar = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 240, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(162, 171, 195));
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "username", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14), new java.awt.Color(100, 110, 130))); // NOI18N
        jTextField1.setDisabledTextColor(new java.awt.Color(162, 171, 195));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(70, 70, 231, 44);

        jTextField2.setBackground(new java.awt.Color(162, 171, 195));
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "e mail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14), new java.awt.Color(100, 110, 130))); // NOI18N
        jTextField2.setDisabledTextColor(new java.awt.Color(162, 171, 195));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(70, 120, 231, 44);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(162, 171, 195));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "bio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(100, 110, 130))); // NOI18N
        jTextArea1.setCaretColor(new java.awt.Color(162, 171, 195));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 240, 231, 70);

        jButton1.setBackground(new java.awt.Color(213, 184, 212));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton1.setText("LOGİN");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 450, 90, 30);

        jButton2.setBackground(new java.awt.Color(213, 184, 212));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton2.setText("SİGN UP");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 450, 90, 30);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(100, 110, 130));
        jCheckBox1.setText("show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(210, 220, 130, 20);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(162, 171, 195));
        jLabel2.setText("CHATPATT");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 10, 180, 50);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel3.setText("CHATPATT");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 10, 190, 58);

        jPasswordField1.setBackground(new java.awt.Color(162, 171, 195));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14), new java.awt.Color(100, 110, 130))); // NOI18N
        jPasswordField1.setDisabledTextColor(new java.awt.Color(162, 171, 195));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(70, 170, 230, 44);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(100, 110, 130));
        jRadioButton1.setText("male");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(80, 320, 70, 22);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(100, 110, 130));
        jRadioButton2.setText("female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(200, 320, 98, 21);

        avatar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male 1", "male 2", "male 3", "female 1", "female 2", "female 3" }));
        avatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarActionPerformed(evt);
            }
        });
        jPanel1.add(avatar);
        avatar.setBounds(120, 400, 90, 20);

        image.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        image.setForeground(new java.awt.Color(100, 110, 130));
        image.setText("Choose avatar");
        jPanel1.add(image);
        image.setBounds(70, 350, 200, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = jTextField1.getText();
        String email = jTextField2.getText();
        String password = new String(jPasswordField1.getPassword());
        String bio = jTextArea1.getText();
        String gender = jRadioButton1.isSelected() ? "male" : "female";
        String profilePicturePath = ""; // Avatar seçimini gerçekleştirdiğiniz yolu buraya ekleyin

        // Seçilen avatarı belirleyin
        if (avatar.isVisible()) {
            if (avatar.getSelectedItem().equals("male 1")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\1.png";
            } else if (avatar.getSelectedItem().equals("male 2")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\3.png";
            } else if (avatar.getSelectedItem().equals("male 3")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\2.png";
            }
        } if (avatar.isVisible()) {
            if (avatar.getSelectedItem().equals("female 1")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\1.png";
            } else if (avatar.getSelectedItem().equals("female 2")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\2.png";
            } else if (avatar.getSelectedItem().equals("female 3")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\3.png";
            }
        }

        // Kullanıcı verilerini kaydet
        saveUser(username, email, password, bio, gender, profilePicturePath);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login loginFrame = new login();
        loginFrame.setVisible(true);
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0); // Şifreyi göster
        } else {
            jPasswordField1.setEchoChar('*'); // Şifreyi gizle
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void avatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarActionPerformed
        // TODO add your handling code here:
        if (avatar.getSelectedItem() == "male 1") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\1.png");
            image.setIcon(images);
        } else if (avatar.getSelectedItem() == "male 2") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\3.png");
            image.setIcon(images);
        } else if (avatar.getSelectedItem() == "male 3") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\2.png");
            image.setIcon(images);
            
        }
        else if (avatar.getSelectedItem() == "female 1") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\1.png");
            image.setIcon(images);
        } else if (avatar.getSelectedItem() == "female 2") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\2.png");
            image.setIcon(images);
        } else if (avatar.getSelectedItem() == "female 3") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\3.png");
            image.setIcon(images);
        }
          
    }//GEN-LAST:event_avatarActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        login loginFrame = new login();
        loginFrame.setVisible(true);
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> avatar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
