/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatpatt;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rana
 */
public class upadateprogile extends javax.swing.JFrame {

    /**
     * Creates new form upadateprogile
     */
    public upadateprogile() {
        initComponents();
         loadUserProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        biog = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        şifre = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        male = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 171, 195));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(null);

        biog.setBackground(new java.awt.Color(238, 240, 252));
        biog.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "bio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        biog.setDisabledTextColor(new java.awt.Color(162, 171, 195));
        biog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biogActionPerformed(evt);
            }
        });
        jPanel1.add(biog);
        biog.setBounds(70, 280, 231, 50);

        user.setBackground(new java.awt.Color(238, 240, 252));
        user.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "username", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        user.setDisabledTextColor(new java.awt.Color(162, 171, 195));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user);
        user.setBounds(70, 164, 231, 50);

        jButton1.setBackground(new java.awt.Color(238, 240, 252));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("save");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 420, 130, 44);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\panda.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 410, 40, 50);

        avatar.setBackground(new java.awt.Color(162, 171, 195));
        avatar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avatar.setText("MY AVATAR");
        jPanel1.add(avatar);
        avatar.setBounds(210, 100, 180, 70);

        email.setBackground(new java.awt.Color(238, 240, 252));
        email.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "e mail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        email.setDisabledTextColor(new java.awt.Color(162, 171, 195));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(70, 220, 231, 50);

        şifre.setBackground(new java.awt.Color(238, 240, 252));
        şifre.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        şifre.setDisabledTextColor(new java.awt.Color(162, 171, 195));
        şifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                şifreActionPerformed(evt);
            }
        });
        jPanel1.add(şifre);
        şifre.setBounds(70, 340, 230, 44);

        jButton3.setBackground(new java.awt.Color(238, 240, 252));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\home.png")); // NOI18N
        jButton3.setText("Home page");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 420, 130, 44);

        male.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male 1", "male 2", "male 3", "female 1", "female 2", "female 3" }));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(130, 20, 90, 20);

        image.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        image.setText("Choose avatar");
        jPanel1.add(image);
        image.setBounds(110, 50, 200, 50);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(220, 390, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biogActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void şifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_şifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_şifreActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ana anaFrame = new ana();
        anaFrame.setVisible(true);
        anaFrame.pack();
        anaFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateUserProfile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        if (male.getSelectedItem() == "male 1") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\1.png");
            image.setIcon(images);
        } else if (male.getSelectedItem() == "male 2") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\3.png");
            image.setIcon(images);
        } else if (male.getSelectedItem() == "male 3") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\2.png");
            image.setIcon(images);
        }
         else if (male.getSelectedItem() == "female 1") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\1.png");
            image.setIcon(images);
        } else if (male.getSelectedItem() == "female 2") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\2.png");
            image.setIcon(images);
        } else if (male.getSelectedItem() == "female 3") {
            ImageIcon images = new ImageIcon("C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\3.png");
            image.setIcon(images);
        }
    }//GEN-LAST:event_maleActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
       if (jCheckBox1.isSelected()) {
            şifre.setEchoChar((char) 0); // Şifreyi göster
        } else {
            şifre.setEchoChar('*'); // Şifreyi gizle
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed
 private void loadUserProfile() {
        String query = "SELECT username, email, bio, profile_picture FROM user WHERE username = ?";
        String username = UserSession.getInstance().getUsername();

        try (Connection conn = db.getConnection(); PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, username);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                String emailText = rs.getString("email");
                String bioText = rs.getString("bio");
                String avatarPath = rs.getString("profile_picture");

                user.setText(username);
                email.setText(emailText);
                biog.setText(bioText);

                if (avatarPath != null && !avatarPath.isEmpty()) {
                    ImageIcon avatarIcon = new ImageIcon(avatarPath);
                    image.setIcon(avatarIcon);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage());
            e.printStackTrace();
        }
    }

     private void updateUserProfile() {
        String username = UserSession.getInstance().getUsername();
        String emailText = email.getText();
        String passwordText = new String(şifre.getPassword());
        String bioText = biog.getText();
        String profilePicturePath = ""; // Avatar seçimini gerçekleştirdiğiniz yolu buraya ekleyin

        // Regex ile kullanıcı adı, e-posta ve şifre doğrulama
       
        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
        String passwordRegex = "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,20}$";

        
        Pattern emailPattern = Pattern.compile(emailRegex);
        Pattern passwordPattern = Pattern.compile(passwordRegex);

       
        Matcher emailMatcher = emailPattern.matcher(emailText);
        Matcher passwordMatcher = passwordPattern.matcher(passwordText);

        
        if (!emailMatcher.matches()) {
            JOptionPane.showMessageDialog(null, "Geçersiz e-posta adresi.");
            return;
        }

        if (!passwordMatcher.matches()) {
            JOptionPane.showMessageDialog(null, "Geçersiz şifre. Şifre en az bir harf ve bir rakam içermeli ve 6-20 karakter uzunluğunda olmalıdır.");
            return;
        }

        // Seçilen avatarı belirleyin
        if (male.isVisible()) {
            if (male.getSelectedItem().equals("male 1")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\1.png";
            } else if (male.getSelectedItem().equals("male 2")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\2.png";
            } else if (male.getSelectedItem().equals("male 3")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\maleicon\\3.png";
            }
        }if (male.isVisible()) {
            if (male.getSelectedItem().equals("female 1")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\1.png";
            } else if (male.getSelectedItem().equals("female 2")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\2.png";
            } else if (male.getSelectedItem().equals("female 3")) {
                profilePicturePath = "C:\\Users\\Rana\\Documents\\NetBeansProjects\\chatpatt\\src\\İCON\\femaleicon\\3.png";
            }
        }

        // Kullanıcı verilerini güncelle
        updateUserProfile(username, emailText, passwordText, bioText, profilePicturePath);
    }

    private void updateUserProfile(String username, String email, String password, String bio, String profilePicturePath) {
        String query = "UPDATE user SET email = ?, password = ?, bio = ?, profile_picture = ? WHERE username = ?";

        try (Connection conn =db.getConnection(); PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, email);
            stmt.setString(2, password);
            stmt.setString(3, bio);
            stmt.setString(4, profilePicturePath);
            stmt.setString(5, username);

            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Profile updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Username does not exist!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upadateprogile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upadateprogile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upadateprogile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upadateprogile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upadateprogile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JTextField biog;
    private javax.swing.JTextField email;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> male;
    private javax.swing.JTextField user;
    private javax.swing.JPasswordField şifre;
    // End of variables declaration//GEN-END:variables
}
